sudo: required

addons:
  apt:
    packages:
    - binfmt-support
    - expect

language: ruby

services:
  - docker

script:
    - sudo bash ./build-docker.sh

after_success:
    - sudo bash ./deploy.sh
