 env:
    global:
        - secure: Vu43feeCyT3WodCdCQLNMdktJ4BGcZv3o3n+buKt3EZNvjmUh6gL0QX+ZrVN2csZYHpPUmQQQnYEqOjveyzOILXbl8QF2u365iEo2ph/7b9nyBRN75pQmc95CuLGVx82TCTsqJX/4psMCu3qdwhtgbJ2srrIlnFmIwGLFziwXZH9lPqdGgffUYN/itAKi8pls/oktedISbqOAcDqRO9zf9CUZNqk6tSsbbQ/hTPnH/COXHyN/KAJTzNT0Fy3lq6laW0Wu7bDDloT/3JXxc3aHlXmlQR5j0yJZ6N9dO+C+2dlk1IrbiGHyrOSwDoBKUYJlyeYyfhVBMWySTc8sjwpTNZY8pu1hFOHbRTw2pswT7SKHiAYXpFjHgxA9N4hRx2kWB1Cwdu17nlHfl8405OTjy2wOyLv6ydCds7SLb+DoAJBd/6E4J364cGPBCc5898OvSr3CiRhRJ9d1us9pmZSR7omER2Q3a2K5TGi3t9SDhmRH69JnXds24Xef4XeIT4drIzUv5hdNyweCjuvqbJ04rbOW2I6+9LE0AT8bAoLNMW5BODOVEyyhs//OrjeQapdixg5A6TQ3ADDZr6aWHK91jbX3qIJqKa6pBe54lrR4JVHInaYyLzjuwOR25MKgvyzb1qrxwwXQMZUZE+deBX/TWxVUhf5/KPFOcZhlLonGeQ=
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - quilt
    - qemu-user-static
    - realpath
    - parted
    - debootstrap
    - dosfstools
    - zip
    - zerofree
    - pxz
    - bsdtar
    - libcap2-bin
    - grep
    - rsync
script:
    - chmod +x ./deploy.sh
    - sudo bash ./build.sh
after_success:
    - sudo bash ./deploy.sh